use_frameworks!

platform :ios, '8.0'

target 'ISWToolkit_Example' do
  pod 'ISWToolkit', :path => '../'

  target 'ISWToolkit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
